import type { AILayerMetadata } from "../../ai/types";

export type LayerType = "image" | "text" | "shape" | "group" | "adjustment" | "3d-scene" | "3d-object" | "3d-group";

export type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "soft-light"
  | "hard-light"
  | "darken"
  | "lighten"
  | "difference"
  | "exclusion"
  | "color-dodge"
  | "color-burn"
  | "hue"
  | "saturation"
  | "color"
  | "luminosity";

export type ShapeKind =
  | "rect"
  | "roundedRect"
  | "ellipse"
  | "line"
  | "arrow"
  | "polygon"
  | "star"
  | "path";

export type TextAlign = "left" | "center" | "right" | "justify";

export type TextDirection = "ltr" | "rtl";

export type AdjustmentKind =
  | "brightness"
  | "contrast"
  | "gamma"
  | "saturation"
  | "exposure"
  | "hue"
  | "temperature"
  | "vibrance"
  | "colorBalance"
  | "shadows"
  | "highlights"
  | "levels"
  | "curves"
  | "equalize"
  | "tint"
  | "blackWhite"
  | "channelMixer"
  | "selectiveColor"
  | "gradientMap"
  | "colorLookup";

/** The single source of truth for every adjustment the editor can express. */
export type AdjustmentType = AdjustmentKind;

export type FilterKind =
  | "gaussianBlur"
  | "meanBlur"
  | "medianFilter"
  | "sharpen"
  | "laplacian"
  | "sobel"
  | "prewitt";

export type ProcessKind = AdjustmentKind | FilterKind;

export interface LayerTransform {
  x: number;
  y: number;
  width: number;
  height: number;
  rotation: number;
  scaleX: number;
  scaleY: number;
  skewX: number;
  skewY: number;
}

/** Adjusted values baked onto a product layer by the product-compositing
 *  pipeline. Stored as metadata so the panel can reflect the last applied
 *  values and projects can round-trip them. Persisted as plain JSON. */
export interface ProductLightingValues {
  brightness: number;
  contrast: number;
  saturation: number;
  temperature: number;
  tint: number;
  exposure: number;
  highlights: number;
  shadows: number;
}

export function emptyProductLighting(): ProductLightingValues {
  return {
    brightness: 0,
    contrast: 0,
    saturation: 0,
    temperature: 0,
    tint: 0,
    exposure: 0,
    highlights: 0,
    shadows: 0,
  };
}

export type ProductSegmentOrigin = "none" | "ai" | "manual" | "mock" | "canvas";

/** Non-destructive metadata for a Product-Compositing layer. Lives on the
 *  ImageLayer; save/load round-trips it as plain JSON. */
export interface ProductCompositeMetadata {
  role: "product";
  sourceName: string | null;
  sourceWidth: number;
  sourceHeight: number;
  /** How the current cutout came to exist. */
  segmentOrigin: ProductSegmentOrigin;
  segmentOperation: string | null;
  segmentProvider: string | null;
  segmentModel: string | null;
  segmentPrompt: string | null;
  importedAt: number;
  /** Lighting values that were baked into the pixels (informational). */
  lighting: ProductLightingValues;
  /** Values baked by the color-match operation. */
  colorMatch: ProductLightingValues;
  /** Recorded when AI / smart-placement positioned the product. */
  smartPlace: { ai: boolean; operation: string | null; provider: string | null; x: number; y: number; width: number; height: number } | null;
  perspectiveMatched: { ai: boolean; operation: string | null; provider: string | null; skewX: number; skewY: number } | null;
  /** Pristine-source snapshot id (used so repeated lighting bakes stay stable). */
  sourceImageId: string | null;
}

/** Metadata for a shadow/reflection layer generated by the product pipeline.
 *  Plain JSON — save/load round-trips it. */
export interface ProductShadowMetadata {
  mode: "shadow" | "reflection" | null;
  productLayerId: string | null;
  opacity: number;
  blur: number;
  distance: number;
  angle: number;
  spread: number;
  tinted: number;
  segments: number;
  generatedAt: number;
}

export function identityTransform(x: number, y: number, width: number, height: number): LayerTransform {
  return { x, y, width, height, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 };
}

/** Grayscale layer mask: pixels stored in the mask store as a canvas whose
 *  alpha channel encodes the mask value (255 = fully visible, 0 = hidden). */
export interface LayerMaskRef {
  id: string;
  enabled: boolean;
  /** When true the mask moves/skews/rotates together with the layer content
   *  (the default Photoshop behaviour). When false the mask stays fixed while
   *  the layer is transformed. */
  linked: boolean;
}

export interface BaseLayer {
  id: string;
  name: string;
  type: LayerType;
  visible: boolean;
  locked: boolean;
  opacity: number;
  blendMode: BlendMode;
  transform: LayerTransform;
  parentId: string | null;
  /** id of a layer whose alpha becomes the visible boundary for this layer. */
  clipTo: string | null;
  mask: LayerMaskRef | null;
  /** Optional AI-generation metadata (non-destructive, informational only). */
  ai?: AILayerMetadata | null;
  /** Optional non-destructive layer styles (rendered at composite time, never
   *  baked into pixels). Absent/null = no styles. */
  styles?: LayerStyles | null;
}

/** ── Layer Styles ───────────────────────────────────────────────────── */

export interface LayerStyleEffect {
  /** Master on/off switch for this effect. */
  enabled: boolean;
}

export interface DropShadowStyle extends LayerStyleEffect {
  kind: "dropShadow";
  offsetX: number;
  offsetY: number;
  blur: number;
  color: string;
  opacity: number;
}

export interface InnerShadowStyle extends LayerStyleEffect {
  kind: "innerShadow";
  offsetX: number;
  offsetY: number;
  blur: number;
  color: string;
  opacity: number;
}

export interface OuterGlowStyle extends LayerStyleEffect {
  kind: "outerGlow";
  blur: number;
  spread: number;
  color: string;
  opacity: number;
}

export interface InnerGlowStyle extends LayerStyleEffect {
  kind: "innerGlow";
  blur: number;
  spread: number;
  color: string;
  opacity: number;
}

export interface StrokeStyle extends LayerStyleEffect {
  kind: "stroke";
  color: string;
  width: number;
  position: "inside" | "center" | "outside";
  opacity: number;
}

export interface ColorOverlayStyle extends LayerStyleEffect {
  kind: "colorOverlay";
  color: string;
  opacity: number;
}

export interface GradientOverlayStyle extends LayerStyleEffect {
  kind: "gradientOverlay";
  gradient: "linear" | "radial";
  /** Angle in degrees (clockwise from +X) used by the linear gradient axis. */
  angle: number;
  stops: { pos: number; color: string }[];
  opacity: number;
}

export interface BevelStyle extends LayerStyleEffect {
  kind: "bevel";
  /** Bevel size in px (radius of the edge band). */
  size: number;
  /** Light direction in degrees. */
  angle: number;
  /** 0..1 how hard the light/shadow contrast is. */
  depth: number;
  highlightColor: string;
  shadowColor: string;
  opacity: number;
}

export type LayerStyleKind = "dropShadow" | "innerShadow" | "outerGlow" | "innerGlow" | "stroke" | "colorOverlay" | "gradientOverlay" | "bevel";

export type LayerStyle =
  | DropShadowStyle
  | InnerShadowStyle
  | OuterGlowStyle
  | InnerGlowStyle
  | StrokeStyle
  | ColorOverlayStyle
  | GradientOverlayStyle
  | BevelStyle;

/** All style effects available on a layer. A null slot means the effect is
 *  absent (this is the serialized default so old projects round-trip cleanly). */
export interface LayerStyles {
  dropShadow: DropShadowStyle | null;
  innerShadow: InnerShadowStyle | null;
  outerGlow: OuterGlowStyle | null;
  innerGlow: InnerGlowStyle | null;
  stroke: StrokeStyle | null;
  colorOverlay: ColorOverlayStyle | null;
  gradientOverlay: GradientOverlayStyle | null;
  bevel: BevelStyle | null;
}

export function emptyLayerStyles(): LayerStyles {
  return {
    dropShadow: null,
    innerShadow: null,
    outerGlow: null,
    innerGlow: null,
    stroke: null,
    colorOverlay: null,
    gradientOverlay: null,
    bevel: null,
  };
}

export const LAYER_STYLE_KINDS: LayerStyleKind[] = [
  "dropShadow", "innerShadow", "outerGlow", "innerGlow", "stroke",
  "colorOverlay", "gradientOverlay", "bevel",
];

/** True when at least one style effect is present AND enabled. */
export function hasAnyStyle(styles: LayerStyles | null | undefined): boolean {
  if (!styles) return false;
  return LAYER_STYLE_KINDS.some((k) => styles[k] !== null && styles[k]!.enabled);
}

export function cloneLayerStyles(styles: LayerStyles | null | undefined): LayerStyles | null {
  if (!styles) return null;
  const out = emptyLayerStyles();
  const rec = out as Record<LayerStyleKind, LayerStyle | null>;
  for (const key of LAYER_STYLE_KINDS) {
    const v = styles[key];
    rec[key] = v ? { ...v } : null;
  }
  return out;
}

/** UI defaults for each effect type when the user first adds it. */
export function defaultLayerStyle(kind: LayerStyleKind): LayerStyle {
  switch (kind) {
    case "dropShadow":
      return { kind, enabled: true, offsetX: 0, offsetY: 4, blur: 6, color: "#000000", opacity: 0.4 };
    case "innerShadow":
      return { kind, enabled: true, offsetX: 0, offsetY: 4, blur: 5, color: "#000000", opacity: 0.4 };
    case "outerGlow":
      return { kind, enabled: true, blur: 8, spread: 0, color: "#7ab8ff", opacity: 0.6 };
    case "innerGlow":
      return { kind, enabled: true, blur: 8, spread: 0, color: "#7ab8ff", opacity: 0.6 };
    case "stroke":
      return { kind, enabled: true, color: "#000000", width: 2, position: "center", opacity: 1 };
    case "colorOverlay":
      return { kind, enabled: true, color: "#ff5a5a", opacity: 1 };
    case "gradientOverlay":
      return { kind, enabled: true, gradient: "linear", angle: 90, stops: [{ pos: 0, color: "#ffffff" }, { pos: 1, color: "#000000" }], opacity: 1 };
    case "bevel":
      return { kind, enabled: true, size: 5, angle: 120, depth: 0.5, highlightColor: "#ffffff", shadowColor: "#000000", opacity: 1 };
  }
}

export interface ImageLayer extends BaseLayer {
  type: "image";
  imageId: string;
  /** Product-Compositing metadata (present on product layers). Non-destructive,
   *  informational only — pixels never depend on it for rendering. */
  product?: ProductCompositeMetadata | null;
  /** Contact-shadow / reflection metadata for layers generated by the product
   *  pipeline. Informational only. */
  shadow?: ProductShadowMetadata | null;
}

export interface TextShadow {
  offsetX: number;
  offsetY: number;
  blur: number;
  color: string;
  opacity: number;
}

export interface TextLayer extends BaseLayer {
  type: "text";
  text: string;
  fontFamily: string;
  fontSize: number;
  fontWeight: number;
  fontStyle: "normal" | "italic";
  color: string;
  align: TextAlign;
  direction: TextDirection;
  letterSpacing: number;
  lineHeight: number;
  autoFit: boolean;
  /** When true, text is clipped to the layer transform box. */
  overflowHidden: boolean;
  /** Optional outline color (null = no outline). */
  stroke: string | null;
  /** Outline thickness in px. */
  strokeWidth: number;
  /** Optional drop shadow. */
  shadow: TextShadow | null;
  /** Optional polyline path (layer-local coords) for text-on-path rendering. */
  textPath?: { points: number[][] } | null;
}

/** A Bezier anchor point in layer-local space. `inX/inY` and `outX/outY` are
 *  the control-handle offsets relative to the anchor (0,0 = no handle). When
 *  `smooth` is set and a handle is missing it is derived from the segment
 *  neighbours. */
export interface PathPoint {
  x: number;
  y: number;
  inX: number;
  inY: number;
  outX: number;
  outY: number;
  smooth: boolean;
}

export interface ShapeLayer extends BaseLayer {
  type: "shape";
  shape: ShapeKind;
  fill: string | null;
  stroke: string | null;
  strokeWidth: number;
  /** Corner radius for roundedRect (px in local space). */
  cornerRadius: number;
  /** Number of sides for polygon / star. */
  points: number;
  /** Inner radius ratio (0..1) for stars. */
  starRatio: number;
  /** Anchor points for the "path" kind, in local (transform) space. When the
   *  first point equals the last point the path is closed (and is fillable). */
  pathPoints?: number[][] | null;
  /** Optional Bezier path data for the "path" kind. Written together with
   *  `pathPoints` so legacy projects and previews stay compatible. */
  pathData?: PathPoint[] | null;
}

export interface AdjustmentParams {
  brightness?: number;
  contrast?: number;
  gamma?: number;
  saturation?: number;
  exposure?: number;
  hue?: number;
  temperature?: number;
  vibrance?: number;
  colorBalance?: { shadows: number; midtones: number; highlights: number };
  levels?: { black: number; mid: number; white: number };
  curves?: number[][];
  equalize?: boolean;
  /** Tint: signed amount toward magenta (+) / green (−), −100..100. */
  tint?: number;
  /** Black & white: per-channel red/green/blue mixing weights. */
  blackWhite?: { red: number; green: number; blue: number };
  /** Channel mixer: output = r*R + g*G + b*B per channel (rows 0..1). */
  channelMixer?: {
    red: { r: number; g: number; b: number };
    green: { r: number; g: number; b: number };
    blue: { r: number; g: number; b: number };
  };
  /** Selective color: signed per-colour-region adjustment (−100..100). */
  selectiveColor?: {
    reds: number;
    yellows: number;
    greens: number;
    cyans: number;
    blues: number;
    magentas: number;
    whites: number;
    neutrals: number;
    blacks: number;
  };
  /** Gradient map: ordered luminance stops (pos 0..1, hex color). */
  gradientMap?: { stops: { pos: number; color: string }[] };
  /** Color lookup: identity / grayscale / invert / sepia built-ins. */
  colorLookup?: { lut: "identity" | "grayscale" | "invert" | "sepia" };
}

export interface AdjustmentLayer extends BaseLayer {
  type: "adjustment";
  adjustment: AdjustmentKind;
  amount: number;
  /** Extended parameters for levels/curves/color-balance style adjustments. */
  params: AdjustmentParams | null;
}

/**
 * 3D layer types. Each carries an `imageId` exactly like an ImageLayer: the
 * 3D runtime rasterizes the referenced scene/object into that pixelStore
 * buffer, so 2D compositing (masks, clips, blend modes, opacity) reuses the
 * existing pipeline verbatim. Non-destructive — the original scene stays
 * editable and re-rasterizes on demand.
 */
export interface Scene3DLayer extends BaseLayer {
  type: "3d-scene";
  sceneId: string;
  imageId: string;
}

export interface Object3DLayer extends BaseLayer {
  type: "3d-object";
  sceneId: string;
  objectId: string;
  imageId: string;
}

export interface Group3DLayer extends BaseLayer {
  type: "3d-group";
  sceneId: string;
  objectId: string;
  imageId: string;
}

export interface GroupLayer extends BaseLayer {
  type: "group";
  collapsed: boolean;
}

export type Layer = ImageLayer | TextLayer | ShapeLayer | AdjustmentLayer | GroupLayer | Scene3DLayer | Object3DLayer | Group3DLayer;

export type EditableLayer = ImageLayer | TextLayer | ShapeLayer;

/** 3D layer types (composited like images but driven by the 3D runtime). */
export const THREE_D_LAYER_TYPES: readonly LayerType[] = ["3d-scene", "3d-object", "3d-group"];

export function is3DDLayer(l: Layer): l is Scene3DLayer | Object3DLayer | Group3DLayer {
  return l.type === "3d-scene" || l.type === "3d-object" || l.type === "3d-group";
}

/** Capability checks */
export const BLEND_MODES: readonly BlendMode[] = [
  "normal",
  "multiply",
  "screen",
  "overlay",
  "soft-light",
  "hard-light",
  "darken",
  "lighten",
  "difference",
  "exclusion",
  "color-dodge",
  "color-burn",
  "hue",
  "saturation",
  "color",
  "luminosity",
];

export const SHAPE_KINDS: readonly ShapeKind[] = [
  "rect",
  "roundedRect",
  "ellipse",
  "line",
  "arrow",
  "polygon",
  "star",
  "path",
];

export const ADJUSTMENT_KINDS: readonly AdjustmentKind[] = [
  "brightness",
  "contrast",
  "gamma",
  "saturation",
  "exposure",
  "hue",
  "temperature",
  "vibrance",
  "colorBalance",
  "shadows",
  "highlights",
  "levels",
  "curves",
  "equalize",
  "tint",
  "blackWhite",
  "channelMixer",
  "selectiveColor",
  "gradientMap",
  "colorLookup",
];

/** Human-readable label per adjustment kind (used to name created layers). */
export const ADJUSTMENT_LABELS: Record<AdjustmentKind, string> = {
  brightness: "Brightness",
  contrast: "Contrast",
  gamma: "Gamma",
  saturation: "Saturation",
  exposure: "Exposure",
  hue: "Hue",
  temperature: "Temperature",
  vibrance: "Vibrance",
  colorBalance: "Color Balance",
  shadows: "Shadows",
  highlights: "Highlights",
  levels: "Levels",
  curves: "Curves",
  equalize: "Equalize",
  tint: "Tint",
  blackWhite: "Black & White",
  channelMixer: "Channel Mixer",
  selectiveColor: "Selective Color",
  gradientMap: "Gradient Map",
  colorLookup: "Color Lookup",
};

export function isImageLayer(l: Layer): l is ImageLayer {
  return l.type === "image";
}
export function isTextLayer(l: Layer): l is TextLayer {
  return l.type === "text";
}
export function isShapeLayer(l: Layer): l is ShapeLayer {
  return l.type === "shape";
}
export function isAdjustmentLayer(l: Layer): l is AdjustmentLayer {
  return l.type === "adjustment";
}
export function isGroupLayer(l: Layer): l is GroupLayer {
  return l.type === "group";
}
export function isEditable(l: Layer): l is EditableLayer {
  return l.type === "image" || l.type === "text" || l.type === "shape";
}
export function isScene3DLayer(l: Layer): l is Scene3DLayer {
  return l.type === "3d-scene";
}
export function isObject3DLayer(l: Layer): l is Object3DLayer {
  return l.type === "3d-object";
}
export function isGroup3DLayer(l: Layer): l is Group3DLayer {
  return l.type === "3d-group";
}

export interface DocumentInfo {
  width: number;
  height: number;
}